#!/usr/bin/env ruby

selector = ARGV.size > 0 ? "#{ARGV.first}/**/*" : '**/*'
fix = (ARGV.size > 1 and ARGV.last == 'fix')

puts "Scanning #{selector}..."

Dir[selector].each do |path|
    next if not File.file?(path)

    file, line_number, new, changed = File.read(path), 0, Array.new, false

    file.each_line do |line|
        line_number += 1

        if line.size != line.rstrip.size + $/.size # Don't forget about the newline character.
            puts "Trailing whitespace(s) in #{path}, line #{line_number}."
            changed = true
        end

        new.push(line.rstrip)
    end

    if fix and changed
        puts "Fixing #{path} where needed..."

        File.write(path, new.join($/) + $/)
    end
end

puts 'Done!'

# vim: syntax=ruby
